functionsDirectory = "C:\\OIBSIP\\WebDev-L2-LoginAuthenticationSystem\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\OIBSIP\\WebDev-L2-LoginAuthenticationSystem\\client\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\OIBSIP\\WebDev-L2-LoginAuthenticationSystem"
command = "npm run build:netlify"
functions = "C:\\OIBSIP\\WebDev-L2-LoginAuthenticationSystem\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/api/*"

[headers.values]
Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Credentials = "true"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]